### ISSUE TITLE
IllegalAccessException on Java 11

### ISSUE THREAD

**Issue by stuarthalloway** [cognitect-labs/REBL-distro#10] opened 2018-12-10 15:29 UTC
1. Download JavaFX manually from https://openjfx.io/openjfx-docs/#install-javafx and unzip the .tgz

2. Add extra deps to :extra-deps
```
:extra-deps
{com.cognitect/rebl          #:local{:root "REBL-0.9.109.jar"}
 org.openjfx/javafx-fxml     #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.fxml.jar"}
 org.openjfx/javafx-controls #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.controls.jar"}
 org.openjfx/javafx-swing    #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.swing.jar"}
 org.openjfx/javafx-base     #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.base.jar"}
 org.openjfx/javafx-web      #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.web.jar"}
 }
```
3. Add extra :jvm-opts
```
:jvm-opts    ["--module-path" "/Users/xxx/javafx-sdk-11.0.1/lib" "--add-modules=javafx.web,javafx.fxml,javafx.swing,javafx.base,javafx.controls"]
```

After all of that, it will now load properly. However, still getting this exception and I can't figure it out, although the data still displays in plain text:

```
2018-12-07 11:38:20,882 [JavaFX Application Thread] ERROR xxx.core - Uncaught exception on JavaFX Application Thread
java.lang.IllegalAccessException: class clojure.lang.Reflector cannot access class com.sun.webkit.dom.NodeListImpl (in module javafx.web) because module javafx.web does not export com.sun.webkit.dom to unnamed module @569c9762
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:387)
	at cognitect.rebl.fx$get_elements.invokeStatic(fx.clj:271)
	at cognitect.rebl.fx$get_elements.invoke(fx.clj:268)
	at cognitect.rebl.fx$set_webview$reify__11775.changed(fx.clj:294)
```

_Originally posted by @kanwei in https://github.com/cognitect-labs/REBL-distro/issues/7#issuecomment-445291074_

**Comment by puredanger** [comment] 2018-12-11 14:55
I tried this process as follows:

1. Installed Java 11 
2. Downloaded and expanded javafx-sdk-11.0.1 to /Users/alex/Downloads/REBL-0.9.109
3. Used the following deps.edn file:

```clojure
{:deps {}
 :aliases
 {:rebl
   {:extra-deps
     {org.clojure/clojure {:mvn/version "1.10.0-RC2"}
      org.clojure/core.async {:mvn/version "0.4.490"}
      com.cognitect/rebl {:local/root "/Users/alex/Downloads/REBL-0.9.109/REBL-0.9.109.jar"}
      org.openjfx/javafx-fxml     #:local{:root "/Users/alex/code/javafx-sdk-11.0.1/lib/javafx.fxml.jar"}
      org.openjfx/javafx-controls #:local{:root "/Users/alex/code/javafx-sdk-11.0.1/lib/javafx.controls.jar"}
      org.openjfx/javafx-swing    #:local{:root "/Users/alex/code/javafx-sdk-11.0.1/lib/javafx.swing.jar"}
      org.openjfx/javafx-base     #:local{:root "/Users/alex/code/javafx-sdk-11.0.1/lib/javafx.base.jar"}
      org.openjfx/javafx-web      #:local{:root "/Users/alex/code/javafx-sdk-11.0.1/lib/javafx.web.jar"}}
   :jvm-opts ["--module-path" "/Users/alex/code/javafx-sdk-11.0.1/lib" "--add-modules=javafx.web,javafx.fxml,javafx.swing,javafx.base,javafx.controls"]}}}
```

Started with:

```
clj -A:rebl -m cognitect.rebl
```

And everything worked. I did not see any illegal access warnings or errors.

**Comment by kanwei** [comment] 2018-12-11 18:35
Hey @puredanger, seems like you were able to reproduce it, but to clarify, the exception only occurs after clicking on the "Welcome to REBL." in the bottom left panel.

**Comment by puredanger** [comment] 2018-12-11 23:01
Yep, thanks. Fix is in Clojure 1.10.0-RC5.

**Comment by stuarthalloway** [comment] 2018-12-14 16:00
Hi @kanwei,

If you can confirm the fix on your end I will close this.

Thanks for the report!

**Comment by kanwei** [comment] 2018-12-14 16:12
Looks like it's working on clojure 1.10.0-RC5. Thanks!

**Comment by MageMasher** [comment] 2018-12-14 20:45
In order to get this to work on my mac I had to add all the javafx modules, not the subset in the initial post of this issue.

```clojure

           :rebl
           {:extra-deps {org.clojure/clojure {:mvn/version "1.10.0-RC5"}
                         com.cognitect/rebl {:local/root "/Users/jlane/programming/tools/REBL-0.9.109/REBL-0.9.109.jar"}
                         stuarthalloway/reflector {:git/url "https://github.com/stuarthalloway/reflector" :sha "58565dda87195478843d7cfdb71371ed29a573bd"}
                         org.clojure/core.async {:mvn/version "0.4.490"}
                         org.openjfx/javafx-fxml     #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.fxml.jar"}
                         org.openjfx/javafx-controls #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.controls.jar"}
                         org.openjfx/javafx-swing    #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.swing.jar"}
                         org.openjfx/javafx-base     #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.base.jar"}
                         org.openjfx/javafx-media #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.media.jar"}
                         org.openjfx/javafx-graphics #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.graphics.jar"}
                         org.openjfx/javafx-web      #:local{:root "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib/javafx.web.jar"}}
            :jvm-opts ["--module-path" "/Users/jlane/programming/git_repos/javafx-sdk-11.0.1/lib" "--add-modules=javafx.web,javafx.fxml,javafx.swing,javafx.base,javafx.controls,javafx.graphics,javafx.media"]}

```

**Comment by puredanger** [comment] 2019-01-03 15:19
As of the latest version of `clj` (1.10.0.408), you can use Java 11, Clojure 1.10, and javafx via deps without any issues. 

```clojure
{:deps {}
 :aliases
 {:rebl
   {:extra-deps
     {org.clojure/clojure {:mvn/version "1.10.0"}
      org.clojure/core.async {:mvn/version "0.4.490"}
      com.cognitect/rebl {:local/root "/Users/alex/Downloads/REBL-0.9.109/REBL-0.9.109.jar"}
      org.openjfx/javafx-fxml     {:mvn/version "11.0.1"}
      org.openjfx/javafx-controls {:mvn/version "11.0.1"}
      org.openjfx/javafx-swing    {:mvn/version "11.0.1"}
      org.openjfx/javafx-base     {:mvn/version "11.0.1"}
      org.openjfx/javafx-web      {:mvn/version "11.0.1"}}}}}
```

```
clj -R:rebl -m cognitect.rebl
```

**Comment by MageMasher** [comment] 2019-01-07 04:00
Hey @puredanger , I think there is a typo in your last codeblock. 
`clj -R:rebl -m cognitect.repl` => `clj -R:rebl -m cognitect.rebl`

**Comment by puredanger** [comment] 2019-01-07 13:13
Yep, sorry - changed

**Comment by puredanger** [comment] 2020-06-30 18:11
I believe this is all done now, closing.

**Closed as completed by puredanger** 2020-06-30 18:11 UTC
Labels: bug, deps
